# Use postgres/example user/password credentials
version: '3.5'

services:
  web:
    image: nginx:latest
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    restart: always

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB : ${DATABASE_NAME:-api}
      POSTGRES_USER : ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD : ${DATABASE_PASSWORD:-example}
    # ports:
    #   - ${DATABASE_PORT}:5432
    volumes:
      - db_volume:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  api:
    build: .
    depends_on:
     - db
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    # ports:
    #   - 8000

volumes:
  db_volume: