"""Create tables

Revision ID: 01d7ab236560
Revises: ab1bdf152717
Create Date: 2021-12-02 10:36:53.746129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d7ab236560'
down_revision = 'ab1bdf152717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'boards',
        'generic board description',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'locations',
        'Describe a given location were things are',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'sensors',
        'one record per sensor intalled on each things',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'sensortypes',
        'Sensor description',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'things',
        'one record per deployed thing',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'things',
        existing_comment='one record per deployed thing',
        schema=None
    )
    op.drop_table_comment(
        'sensortypes',
        existing_comment='Sensor description',
        schema=None
    )
    op.drop_table_comment(
        'sensors',
        existing_comment='one record per sensor intalled on each things',
        schema=None
    )
    op.drop_table_comment(
        'locations',
        existing_comment='Describe a given location were things are',
        schema=None
    )
    op.drop_table_comment(
        'boards',
        existing_comment='generic board description',
        schema=None
    )
    # ### end Alembic commands ###
