"""Create tables

Revision ID: ab1bdf152717
Revises: 3caf8e7b81a9
Create Date: 2021-12-02 10:28:56.503017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab1bdf152717'
down_revision = '3caf8e7b81a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('sensors', sa.Column('board_id', sa.Integer(), nullable=False))
    op.add_column('sensors', sa.Column('type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sensors', 'sensortypes', ['type_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sensors', 'boards', ['board_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sensors', 'boardid')
    op.drop_column('sensors', 'type')
    op.add_column('things', sa.Column('physical_id', sa.String(), nullable=False))
    op.add_column('things', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('things', sa.Column('board_id', sa.Integer(), nullable=False))
    op.add_column('things', sa.Column('location_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'things', ['physical_id'])
    op.create_foreign_key(None, 'things', 'boards', ['board_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'things', 'locations', ['location_id'], ['id'], ondelete='CASCADE')
    op.drop_column('things', 'boardid')
    op.drop_column('things', 'locationid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('things', sa.Column('locationid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('things', sa.Column('boardid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'things', type_='foreignkey')
    op.drop_constraint(None, 'things', type_='foreignkey')
    op.drop_constraint(None, 'things', type_='unique')
    op.drop_column('things', 'location_id')
    op.drop_column('things', 'board_id')
    op.drop_column('things', 'created_at')
    op.drop_column('things', 'physical_id')
    op.add_column('sensors', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sensors', sa.Column('boardid', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sensors', type_='foreignkey')
    op.drop_constraint(None, 'sensors', type_='foreignkey')
    op.drop_column('sensors', 'type_id')
    op.drop_column('sensors', 'board_id')
    op.drop_column('locations', 'created_at')
    # ### end Alembic commands ###
